# Generated by Django 3.2 on 2022-12-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221214_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'юзер'), (2, 'админ'), (3, 'модератор')], default=1, verbose_name='Роли'),
        ),
    ]
