
# Generated by Django 3.2 on 2022-12-16 20:27


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221214_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[('user', 'юзер'), ('admin', 'админ'), ('moderator', 'модератор')], default='user', verbose_name='Роли'),
        ),
    ]
