# Generated by Django 3.2 on 2022-12-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20221217_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[('user', 'Юзер'), ('admin', 'Админ'), ('moderator', 'Модератор')], default='user', verbose_name='Роли'),
        ),
    ]
