# Generated by Django 3.2 on 2022-12-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[('1', 'Юзер'), ('2', 'Админ'), ('3', 'Модератор')], default='1', verbose_name='Роли'),
        ),
    ]
