# Generated by Django 3.2 on 2022-12-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Юзер'), ('admin', 'Админ'), ('moderator', 'Модератор')], default='user', max_length=10, verbose_name='Роли'),
        ),
    ]
