# Generated by Django 3.2 on 2022-12-21 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_token1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token1',
        ),
    ]
