# Generated by Django 3.2 on 2022-12-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_user_token1'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_token',
            field=models.TextField(blank=True, verbose_name='Токен'),
        ),
    ]
