# Generated by Django 3.2 on 2022-12-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_token',
            field=models.CharField(blank=True, max_length=150, verbose_name='Токен'),
        ),
    ]
