# Generated by Django 3.2 on 2022-12-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221215_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Описание фильма'),
        ),
    ]
